### PR TITLE
Added option for add group only instead of remove prev.

### PR DESCRIPTION
**Pull request by DiegoDaniel**
This PR allow you to decide if you want to remove previous group from user, or just simply add the new ones.

I actually faced this problem and fixed it this way. So, maybe this can help others on the same situation.

First PR of my life so, if something is wrong, let me know to fix it.

### CODE REVIEW

**Comment by okx-code** [comment]
How would this be useful?

**Comment by DiegoDaniel** [comment]
In my case i have diferent permissions on every group.

like:

default: all-basic-perms
group-a: no new perms + default parent.
group-b: new perms for some things + default parent.
group-c: no new perms + default parent.
group-d: new perms for other things + default parent.

If i remove group-b from user to give him group-c, he will lose those perms.

**Comment by NicBOMB** [comment]
> In my case i have diferent permissions on every group.
> 
> like:
> 
> default: all-basic-perms
> group-a: no new perms + default parent.
> group-b: new perms for some things + default parent.
> group-c: no new perms + default parent.
> group-d: new perms for other things + default parent.
> 
> If i remove group-b from user to give him group-c, he will lose those perms.

We suggest using luckperms, which manages permissions for groups. If you want your groups to continue to inherit from previous groups, you can add the previous group as a parent node with `group.<parent_name>`. It should inherit all of the nodes from the previous, including its parents and their nodes. I don't think rankup needs this functionality if your groups have been setup correctly already, but adding the feature doesn't appear detrimental IMO.

**Comment by okx-code** [comment]
You can use `permission-rankup` to perform this function instead.

**Pull request closed without merging**
